// Code generated by protoc-gen-go. DO NOT EDIT.
// source: githubcard.proto

package githubcard

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Issue_IssueState int32

const (
	Issue_OPEN   Issue_IssueState = 0
	Issue_CLOSED Issue_IssueState = 1
)

var Issue_IssueState_name = map[int32]string{
	0: "OPEN",
	1: "CLOSED",
}

var Issue_IssueState_value = map[string]int32{
	"OPEN":   0,
	"CLOSED": 1,
}

func (x Issue_IssueState) String() string {
	return proto.EnumName(Issue_IssueState_name, int32(x))
}

func (Issue_IssueState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{3, 0}
}

type SilenceRequest_SilenceState int32

const (
	SilenceRequest_UNKNOWN   SilenceRequest_SilenceState = 0
	SilenceRequest_SILENCE   SilenceRequest_SilenceState = 1
	SilenceRequest_UNSILENCE SilenceRequest_SilenceState = 2
)

var SilenceRequest_SilenceState_name = map[int32]string{
	0: "UNKNOWN",
	1: "SILENCE",
	2: "UNSILENCE",
}

var SilenceRequest_SilenceState_value = map[string]int32{
	"UNKNOWN":   0,
	"SILENCE":   1,
	"UNSILENCE": 2,
}

func (x SilenceRequest_SilenceState) String() string {
	return proto.EnumName(SilenceRequest_SilenceState_name, int32(x))
}

func (SilenceRequest_SilenceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{5, 0}
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Silence struct {
	Silence              string   `protobuf:"bytes,1,opt,name=silence,proto3" json:"silence,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Silence) Reset()         { *m = Silence{} }
func (m *Silence) String() string { return proto.CompactTextString(m) }
func (*Silence) ProtoMessage()    {}
func (*Silence) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{1}
}

func (m *Silence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Silence.Unmarshal(m, b)
}
func (m *Silence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Silence.Marshal(b, m, deterministic)
}
func (m *Silence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Silence.Merge(m, src)
}
func (m *Silence) XXX_Size() int {
	return xxx_messageInfo_Silence.Size(m)
}
func (m *Silence) XXX_DiscardUnknown() {
	xxx_messageInfo_Silence.DiscardUnknown(m)
}

var xxx_messageInfo_Silence proto.InternalMessageInfo

func (m *Silence) GetSilence() string {
	if m != nil {
		return m.Silence
	}
	return ""
}

func (m *Silence) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type Config struct {
	Silences             []*Silence `protobuf:"bytes,1,rep,name=silences,proto3" json:"silences,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{2}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSilences() []*Silence {
	if m != nil {
		return m.Silences
	}
	return nil
}

type Issue struct {
	Title                string           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string           `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Service              string           `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Number               int32            `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	State                Issue_IssueState `protobuf:"varint,5,opt,name=state,proto3,enum=githubcard.Issue_IssueState" json:"state,omitempty"`
	Sticky               bool             `protobuf:"varint,6,opt,name=sticky,proto3" json:"sticky,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{3}
}

func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (m *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(m, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Issue) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Issue) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Issue) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Issue) GetState() Issue_IssueState {
	if m != nil {
		return m.State
	}
	return Issue_OPEN
}

func (m *Issue) GetSticky() bool {
	if m != nil {
		return m.Sticky
	}
	return false
}

type IssueList struct {
	Issues               []*Issue `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueList) Reset()         { *m = IssueList{} }
func (m *IssueList) String() string { return proto.CompactTextString(m) }
func (*IssueList) ProtoMessage()    {}
func (*IssueList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{4}
}

func (m *IssueList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueList.Unmarshal(m, b)
}
func (m *IssueList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueList.Marshal(b, m, deterministic)
}
func (m *IssueList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueList.Merge(m, src)
}
func (m *IssueList) XXX_Size() int {
	return xxx_messageInfo_IssueList.Size(m)
}
func (m *IssueList) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueList.DiscardUnknown(m)
}

var xxx_messageInfo_IssueList proto.InternalMessageInfo

func (m *IssueList) GetIssues() []*Issue {
	if m != nil {
		return m.Issues
	}
	return nil
}

type SilenceRequest struct {
	Silence              string                      `protobuf:"bytes,1,opt,name=silence,proto3" json:"silence,omitempty"`
	Origin               string                      `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	State                SilenceRequest_SilenceState `protobuf:"varint,2,opt,name=state,proto3,enum=githubcard.SilenceRequest_SilenceState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SilenceRequest) Reset()         { *m = SilenceRequest{} }
func (m *SilenceRequest) String() string { return proto.CompactTextString(m) }
func (*SilenceRequest) ProtoMessage()    {}
func (*SilenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{5}
}

func (m *SilenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SilenceRequest.Unmarshal(m, b)
}
func (m *SilenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SilenceRequest.Marshal(b, m, deterministic)
}
func (m *SilenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SilenceRequest.Merge(m, src)
}
func (m *SilenceRequest) XXX_Size() int {
	return xxx_messageInfo_SilenceRequest.Size(m)
}
func (m *SilenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SilenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SilenceRequest proto.InternalMessageInfo

func (m *SilenceRequest) GetSilence() string {
	if m != nil {
		return m.Silence
	}
	return ""
}

func (m *SilenceRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *SilenceRequest) GetState() SilenceRequest_SilenceState {
	if m != nil {
		return m.State
	}
	return SilenceRequest_UNKNOWN
}

type SilenceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SilenceResponse) Reset()         { *m = SilenceResponse{} }
func (m *SilenceResponse) String() string { return proto.CompactTextString(m) }
func (*SilenceResponse) ProtoMessage()    {}
func (*SilenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfced67e3377ee11, []int{6}
}

func (m *SilenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SilenceResponse.Unmarshal(m, b)
}
func (m *SilenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SilenceResponse.Marshal(b, m, deterministic)
}
func (m *SilenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SilenceResponse.Merge(m, src)
}
func (m *SilenceResponse) XXX_Size() int {
	return xxx_messageInfo_SilenceResponse.Size(m)
}
func (m *SilenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SilenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SilenceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("githubcard.Issue_IssueState", Issue_IssueState_name, Issue_IssueState_value)
	proto.RegisterEnum("githubcard.SilenceRequest_SilenceState", SilenceRequest_SilenceState_name, SilenceRequest_SilenceState_value)
	proto.RegisterType((*Token)(nil), "githubcard.Token")
	proto.RegisterType((*Silence)(nil), "githubcard.Silence")
	proto.RegisterType((*Config)(nil), "githubcard.Config")
	proto.RegisterType((*Issue)(nil), "githubcard.Issue")
	proto.RegisterType((*IssueList)(nil), "githubcard.IssueList")
	proto.RegisterType((*SilenceRequest)(nil), "githubcard.SilenceRequest")
	proto.RegisterType((*SilenceResponse)(nil), "githubcard.SilenceResponse")
}

func init() { proto.RegisterFile("githubcard.proto", fileDescriptor_bfced67e3377ee11) }

var fileDescriptor_bfced67e3377ee11 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xbb, 0x6d, 0x93, 0xb6, 0x53, 0x3d, 0x73, 0xa3, 0xc8, 0x52, 0x15, 0xc2, 0xbe, 0x18,
	0x1f, 0x3c, 0x21, 0x82, 0x22, 0xe2, 0x83, 0xf4, 0xc2, 0x71, 0x58, 0x52, 0x49, 0x3c, 0x7c, 0xbe,
	0x24, 0x6b, 0x5d, 0xee, 0x4c, 0xce, 0xec, 0x46, 0xb8, 0x8f, 0xe5, 0xab, 0x5f, 0xc3, 0x2f, 0x24,
	0xd9, 0xdd, 0xb4, 0x81, 0x9e, 0xd0, 0x97, 0x32, 0xbf, 0xd9, 0x3f, 0x33, 0xff, 0x99, 0x69, 0xc0,
	0xdb, 0x08, 0xf5, 0xbd, 0xc9, 0xf2, 0xcb, 0xba, 0x38, 0xb9, 0xa9, 0x2b, 0x55, 0x21, 0xec, 0x32,
	0xec, 0x19, 0x38, 0x5f, 0xaa, 0x2b, 0x5e, 0xe2, 0x23, 0x70, 0x54, 0x1b, 0x50, 0xe2, 0x93, 0x60,
	0x96, 0x18, 0x60, 0xef, 0x61, 0x92, 0x8a, 0x6b, 0x5e, 0xe6, 0x1c, 0x29, 0x4c, 0xa4, 0x09, 0xad,
	0xa4, 0x43, 0x7c, 0x0c, 0x6e, 0x55, 0x8b, 0x8d, 0x28, 0xe9, 0x50, 0x3f, 0x58, 0x62, 0xef, 0xc0,
	0x5d, 0x56, 0xe5, 0x37, 0xb1, 0xc1, 0x57, 0x30, 0xb5, 0x62, 0x49, 0x89, 0x3f, 0x0a, 0xe6, 0xe1,
	0xc3, 0x93, 0x9e, 0x2d, 0xdb, 0x22, 0xd9, 0x8a, 0xd8, 0x5f, 0x02, 0xce, 0xb9, 0x94, 0x0d, 0xd7,
	0xbe, 0x84, 0xba, 0xe6, 0x5b, 0x5f, 0x2d, 0x20, 0xc2, 0x38, 0xab, 0x8a, 0x5b, 0xdb, 0x50, 0xc7,
	0xda, 0x20, 0xaf, 0x7f, 0x89, 0x9c, 0xd3, 0x91, 0x35, 0x68, 0xb0, 0x35, 0x58, 0x36, 0x3f, 0x32,
	0x5e, 0xd3, 0xb1, 0x4f, 0x02, 0x27, 0xb1, 0x84, 0x21, 0x38, 0x52, 0x5d, 0x2a, 0x4e, 0x1d, 0x9f,
	0x04, 0x47, 0xe1, 0xd3, 0xbe, 0x27, 0xdd, 0xdd, 0xfc, 0xa6, 0xad, 0x26, 0x31, 0xd2, 0xb6, 0x96,
	0x54, 0x22, 0xbf, 0xba, 0xa5, 0xae, 0x4f, 0x82, 0x69, 0x62, 0x89, 0x31, 0x80, 0x9d, 0x18, 0xa7,
	0x30, 0x5e, 0x7f, 0x8e, 0x62, 0x6f, 0x80, 0x00, 0xee, 0x72, 0xb5, 0x4e, 0xa3, 0x53, 0x8f, 0xb0,
	0x37, 0x30, 0xd3, 0x9a, 0x95, 0x90, 0x0a, 0x5f, 0x80, 0x2b, 0x5a, 0xe8, 0x36, 0x72, 0xbc, 0xd7,
	0x3d, 0xb1, 0x02, 0xf6, 0x87, 0xc0, 0x51, 0xb7, 0x23, 0xfe, 0xb3, 0xe1, 0x52, 0x1d, 0x74, 0x8d,
	0x51, 0xff, 0x1a, 0xf8, 0xa1, 0x1b, 0x76, 0xa8, 0x87, 0x7d, 0x7e, 0xd7, 0x01, 0x4c, 0xf1, 0x0e,
	0xfb, 0x73, 0xb3, 0xb7, 0x70, 0xaf, 0x9f, 0xc6, 0x39, 0x4c, 0x2e, 0xe2, 0x4f, 0xf1, 0xfa, 0x6b,
	0x3b, 0xe4, 0x1c, 0x26, 0xe9, 0xf9, 0x2a, 0x8a, 0x97, 0x91, 0x47, 0xf0, 0x3e, 0xcc, 0x2e, 0xe2,
	0x0e, 0x87, 0xec, 0x18, 0x1e, 0x6c, 0xcb, 0xcb, 0x9b, 0xaa, 0x94, 0x3c, 0xfc, 0x4d, 0xc0, 0x3d,
	0xd3, 0xdd, 0x31, 0x84, 0xe9, 0xc7, 0xa2, 0x30, 0xa7, 0xde, 0xdf, 0xc0, 0x62, 0x3f, 0xc5, 0x06,
	0xf8, 0x12, 0x46, 0x67, 0x5c, 0x1d, 0x2c, 0x3f, 0xdd, 0xfd, 0x87, 0x17, 0xff, 0x1f, 0x7a, 0xf1,
	0xe4, 0xce, 0x37, 0xe3, 0x98, 0x0d, 0x32, 0x57, 0x7f, 0x3b, 0xaf, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x37, 0x3c, 0x8f, 0xbd, 0x4f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GithubClient is the client API for Github service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GithubClient interface {
	AddIssue(ctx context.Context, in *Issue, opts ...grpc.CallOption) (*Issue, error)
	Get(ctx context.Context, in *Issue, opts ...grpc.CallOption) (*Issue, error)
	Silence(ctx context.Context, in *SilenceRequest, opts ...grpc.CallOption) (*SilenceResponse, error)
}

type githubClient struct {
	cc *grpc.ClientConn
}

func NewGithubClient(cc *grpc.ClientConn) GithubClient {
	return &githubClient{cc}
}

func (c *githubClient) AddIssue(ctx context.Context, in *Issue, opts ...grpc.CallOption) (*Issue, error) {
	out := new(Issue)
	err := c.cc.Invoke(ctx, "/githubcard.Github/AddIssue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) Get(ctx context.Context, in *Issue, opts ...grpc.CallOption) (*Issue, error) {
	out := new(Issue)
	err := c.cc.Invoke(ctx, "/githubcard.Github/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) Silence(ctx context.Context, in *SilenceRequest, opts ...grpc.CallOption) (*SilenceResponse, error) {
	out := new(SilenceResponse)
	err := c.cc.Invoke(ctx, "/githubcard.Github/Silence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubServer is the server API for Github service.
type GithubServer interface {
	AddIssue(context.Context, *Issue) (*Issue, error)
	Get(context.Context, *Issue) (*Issue, error)
	Silence(context.Context, *SilenceRequest) (*SilenceResponse, error)
}

func RegisterGithubServer(s *grpc.Server, srv GithubServer) {
	s.RegisterService(&_Github_serviceDesc, srv)
}

func _Github_AddIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Issue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).AddIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubcard.Github/AddIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).AddIssue(ctx, req.(*Issue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Issue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubcard.Github/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).Get(ctx, req.(*Issue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_Silence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SilenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).Silence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubcard.Github/Silence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).Silence(ctx, req.(*SilenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Github_serviceDesc = grpc.ServiceDesc{
	ServiceName: "githubcard.Github",
	HandlerType: (*GithubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIssue",
			Handler:    _Github_AddIssue_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Github_Get_Handler,
		},
		{
			MethodName: "Silence",
			Handler:    _Github_Silence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "githubcard.proto",
}
